name: Valist Publish
on:
  release:
    types: [published]
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - uses: robinraju/release-downloader@v1.4
        with:
          repository: "ChainSafe/lodestar"
          latest: true
          tarBall: true
          zipBall: true
          fileName: "*"
      - uses: valist-io/valist-github-action@v2.5.3
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: chainsafe
          project: lodestar
          release: ${{ github.ref_name }}
          path: '.'
